<?php
/**
 * @file
 * Install, update and uninstall functions for the SL7 Receipt module.
 * 
 * @author Semyon Dragunov <sam.dragunov@gmail.com>
 * https://github.com/SemyonDragunov
 */

function sl7_receipt_install() {

}

function sl7_receipt_uninstall() {
  $result = db_select('variable', 'v')
    ->fields('v', array('name'))
    ->condition('name', 'sl7_receipt_%', 'LIKE')
    ->execute();

  foreach ($result as $row) {
    variable_del($row->name);
  }
}